<div class="alert alert-info">
						<button data-dismiss="alert" class="close close-sm" type="button">
							<i class="fa fa-times"></i>
						</button>
						<h3 align="center">INFORMASI</h3><hr>
						<b>Jika sudah mendaftar, silahkan lakukan DEPOSIT SALDO melalui panel ini. Atau kamu bisa chat ke <a href="http://line.me/ti/p/%40ehx3236k" <Line: MUS> LINE MUS. </a> </br></br>
						Membuat akun memang gratis, tapi jika akunmu kosong tanpa saldo maka otomatis akan terhapus. kecuali jika kamu pernah melakukan deposit saldo. </br></b>
						<br> Aplikasi MUS sudah bisa di download <a href="apk_mus.apk">Disini => DOWNLOAD</a>
					</div>